version: '2'
services:
        web:
                build: .
                ports:
                        - "3000:3000"
                volumes:
                        - .:/go/src/app
                env_file:
                        - ./app.env
                depends_on:
                        - mysql

        mysql:
                image: mysql:5.7
                volumes:
                        - /tmp/foobar:/var/lib/mysql
                        - ./sql:/docker-entrypoint-initdb.d
                environment:
                        - MYSQL_ROOT_PASSWORD=root

