version: '2'
services:
        web:
                build: .
                ports:
                        - "3000:3000"
                volumes:
                        - .:/go/src/app
                env_file:
                        - ./app.env
                depends_on:
                        - mysql

        mysql:
                image: mysql:5.7
                volumes:
                        - ./sql:/docker-entrypoint-initdb.d
                volumes_from:
                        - data
                environment:
                        - MYSQL_ROOT_PASSWORD=root
                depends_on:
                        - data

        data:
                image: busybox
                volumes:
                        - /var/lib/mysql
