version: '2'
services:
        web:
                build: .
                links:
                        - mysql
                ports:
                        - "3000:3000"
                volumes:
                        - .:/go/src/app
                environment:
                        - "PORT=3000"
                        - "HOST=0.0.0.0"
        mysql:
               image: mysql:5.7
               environment:
                       - "MYSQL_ROOT_PASSWORD=root"
               volumes:
                       - /tmp/appdatadir:/var/lib/mysql
